trigger:
- main

pool:
  name: 'Default'

variables:
- group: esmos-secrets

steps:
- task: SSH@0
  displayName: 'Deploy ESMOS via Pipeline'
  inputs:
    sshEndpoint: 'ssh-odoo17-staging'
    runOptions: 'commands'
    failOnStdErr: false # This stops Azure from crashing when Docker talks
    commands: |
      # 1. Start clean: wipe the folder and do a fresh clone
      cd /home/G02T04
      sudo rm -rf e08g02t04-esmos-project
      git clone -q https://github.com/Nigellzy/e08g02t04-esmos-project.git
      
      # 2. Go into the fresh project folder
      cd e08g02t04-esmos-project
      
      # 3. Inject the passwords directly into the folder
      echo "POSTGRES_PASSWORD=$(DB_PASSWORD)" > .env
      echo "MARIADB_PASSWORD=$(MOODLE_DB_PASSWORD)" >> .env
      echo "ODOO_ADMIN_PASSWORD=$(ODOO_ADMIN_PASSWORD)" >> .env
      
      # 4. Spin up the containers (Bypassing update_code.sh completely!)
      sudo docker compose down
      sudo docker compose up -d
    readyTimeout: '20000'